RE-1425 RPC Gating VirtualEnv Container Optimizations
- Added lock back around the scp upload and index logic

diff --git a/rpc_jobs/build_gating_venv.yml b/rpc_jobs/build_gating_venv.yml
--- a/rpc_jobs/build_gating_venv.yml
+++ b/rpc_jobs/build_gating_venv.yml
@@ -35,92 +35,119 @@
                 sshagent(credentials:['rpc_repo_ssh_user_private_key']){
                   sh """#!/bin/bash -xeu
 
-                  # The repo path
-                  REPO_PATH="/var/www/repo/rpcgating/venvs"
+                    # The repo path
+                    REPO_PATH="/var/www/repo/rpcgating/venvs"
 
-                  # Determine the SHA and archive name that we'll use
-                  pushd rpc-gating; SHA=\$(git rev-parse HEAD); popd
-                  archive="rpcgatingvenv_\${SHA}.tbz"
+                    # Determine the SHA and archive name that we'll use
+                    pushd rpc-gating; SHA=\$(git rev-parse HEAD); popd
+                    archive="rpcgatingvenv_\${SHA}_test2.tbz"
 
-                  # Set some SSH options
-                  SSH_OPTS="-o StrictHostKeyChecking=no"
+                    # Set some SSH options
+                    SSH_OPTS="-o StrictHostKeyChecking=no"
 
-                  # Check to see if the virtual env archive already exists...if so, no need to rebuild it
-                  set +e # Don't exit on error since we want to evalute the error code and exit cleanly
-                  ssh \$SSH_OPTS \$REPO_USER@\$REPO_HOST "test -e \$REPO_PATH/\$archive"
-                  if [[ \$? -eq 0 ]]; then
-                    echo "Archive \$REPO_PATH/\$archive already exists.  Skipping virtual env build."
-                    exit 0
-                  fi
-                  set -e # Exit on error
+                    # Check to see if the virtual env archive already exists...if so, no need to rebuild it
+                    set +e # Don't exit on error since we want to evalute the error code and exit cleanly
+                    ssh \$SSH_OPTS \$REPO_USER@\$REPO_HOST "test -e \$REPO_PATH/\$archive"
+                    if [[ \$? -eq 0 ]]; then
+                      echo "Archive \$REPO_PATH/\$archive already exists.  Skipping virtual env build."
 
-                  # Install virtualenv if required
-                  if [[ ! -d ".venv" ]]; then
-                    requirements="virtualenv==15.1.0"
-                    pip install -U "\${requirements}" \
-                      || pip install --isolated -U "\${requirements}"
+                      # Touch a skip file to indicate that we should NOT upload it below
+                      touch \$archive.skip.upload
 
-                    if which scl
-                    then
-                      # redhat/centos
-                      source /opt/rh/python27/enable
-                      virtualenv --no-pip --no-setuptools --no-wheel --python=/opt/rh/python27/root/usr/bin/python .venv
-                      # hack the selinux module into the venv
-                      cp -r /usr/lib64/python2.6/site-packages/selinux .venv/lib64/python2.7/site-packages/ ||:
-                    else
-                      virtualenv --no-pip --no-setuptools --no-wheel .venv
+                      exit 0
                     fi
-                  fi
+                    set -e # Exit on error
 
-                  # Install Pip
-                  set +xeu
-                  source .venv/bin/activate
-                  set -xeu
+                    # Install virtualenv if required
+                    if [[ ! -d ".venv" ]]; then
+                      requirements="virtualenv==15.1.0"
+                      pip install -U "\${requirements}" \
+                        || pip install --isolated -U "\${requirements}"
 
-                  # UG-613 change TMPDIR to directory with more space
-                  export TMPDIR="/var/lib/jenkins/tmp"
+                      if which scl
+                      then
+                        # redhat/centos
+                        source /opt/rh/python27/enable
+                        virtualenv --no-pip --no-setuptools --no-wheel --python=/opt/rh/python27/root/usr/bin/python .venv
+                        # hack the selinux module into the venv
+                        cp -r /usr/lib64/python2.6/site-packages/selinux .venv/lib64/python2.7/site-packages/ ||:
+                      else
+                        virtualenv --no-pip --no-setuptools --no-wheel .venv
+                      fi
+                    fi
 
-                  # If the pip version we're using is not the same as the constraint then replace it
-                  PIP_TARGET="\$(awk -F= '/^pip==/ {print \$3}' rpc-gating/constraints.txt)"
-                  VENV_PYTHON=".venv/bin/python"
-                  VENV_PIP=".venv/bin/pip"
-                  if [[ "\$(\${VENV_PIP} --version)" != "pip \${PIP_TARGET}"* ]]; then
-                    # Install a known version of pip, setuptools, and wheel in the venv
-                    CURL_CMD="curl --silent --show-error --retry 5"
-                    OUTPUT_FILE="get-pip.py"
-                    \${CURL_CMD} https://bootstrap.pypa.io/get-pip.py > \${OUTPUT_FILE} \
-                      || \${CURL_CMD} https://raw.githubusercontent.com/pypa/get-pip/master/get-pip.py > \${OUTPUT_FILE}
-                    GETPIP_OPTIONS="pip setuptools wheel --constraint rpc-gating/constraints.txt"
-                    \${VENV_PYTHON} \${OUTPUT_FILE} \${GETPIP_OPTIONS} \
-                      || \${VENV_PYTHON} \${OUTPUT_FILE} --isolated \${GETPIP_OPTIONS}
-                  fi
+                    # Install Pip
+                    set +xeu
+                    source .venv/bin/activate
+                    set -xeu
 
-                  # Install rpc-gating requirements
-                  PIP_OPTIONS="-c rpc-gating/constraints.txt -r rpc-gating/requirements.txt"
-                  \${VENV_PIP} install \${PIP_OPTIONS} \
-                    || \${VENV_PIP} install --isolated \${PIP_OPTIONS}
+                    # UG-613 change TMPDIR to directory with more space
+                    export TMPDIR="/var/lib/jenkins/tmp"
 
-                  # Install ansible roles
-                  mkdir -p rpc-gating/playbooks/roles
-                  ansible-galaxy install -r rpc-gating/role_requirements.yml -p rpc-gating/playbooks/roles
+                    # If the pip version we're using is not the same as the constraint then replace it
+                    PIP_TARGET="\$(awk -F= '/^pip==/ {print \$3}' rpc-gating/constraints.txt)"
+                    VENV_PYTHON=".venv/bin/python"
+                    VENV_PIP=".venv/bin/pip"
+                    if [[ "\$(\${VENV_PIP} --version)" != "pip \${PIP_TARGET}"* ]]; then
+                      # Install a known version of pip, setuptools, and wheel in the venv
+                      CURL_CMD="curl --silent --show-error --retry 5"
+                      OUTPUT_FILE="get-pip.py"
+                      \${CURL_CMD} https://bootstrap.pypa.io/get-pip.py > \${OUTPUT_FILE} \
+                        || \${CURL_CMD} https://raw.githubusercontent.com/pypa/get-pip/master/get-pip.py > \${OUTPUT_FILE}
+                      GETPIP_OPTIONS="pip setuptools wheel --constraint rpc-gating/constraints.txt"
+                      \${VENV_PYTHON} \${OUTPUT_FILE} \${GETPIP_OPTIONS} \
+                        || \${VENV_PYTHON} \${OUTPUT_FILE} --isolated \${GETPIP_OPTIONS}
+                    fi
 
-                  # Tar venv and roles
-                  find .venv -name \\*.pyc -delete
-                  echo "\${PWD}/.venv" > .venv/original_venv_path
-                  echo \$SHA > .venv/venv_sha
-                  tar cjfp \$archive .venv rpc-gating/playbooks/roles
+                    # Install rpc-gating requirements
+                    PIP_OPTIONS="-c rpc-gating/constraints.txt -r rpc-gating/requirements.txt"
+                    \${VENV_PIP} install \${PIP_OPTIONS} \
+                      || \${VENV_PIP} install --isolated \${PIP_OPTIONS}
 
-                  ssh \${SSH_OPTS} \$REPO_USER@\$REPO_HOST "mkdir -p \$REPO_PATH"
+                    # Install ansible roles
+                    mkdir -p rpc-gating/playbooks/roles
+                    ansible-galaxy install -r rpc-gating/role_requirements.yml -p rpc-gating/playbooks/roles
 
-                  # Upload generated version
-                  scp \$SSH_OPTS \$archive \$REPO_USER@\$REPO_HOST:\$REPO_PATH
-
-                  # Generate index
-                  ssh \$SSH_OPTS \$REPO_USER@\$REPO_HOST "cd \$REPO_PATH; ls -1 *tbz > index"
-
-                  # Keep 100 newest archives, remove the rest.
-                  ssh \$SSH_OPTS \$REPO_USER@\$REPO_HOST "cd \$REPO_PATH && ls -t1 *tbz |tail -n +101 |while read f; do echo "'removing \$f'"; rm "'\$f'"; done"
+                    # Tar venv and roles
+                    find .venv -name \\*.pyc -delete
+                    echo "\${PWD}/.venv" > .venv/original_venv_path
+                    echo \$SHA > .venv/venv_sha
+                    tar cjfp \$archive .venv rpc-gating/playbooks/roles
                   """
+
+                  // Lock to prevent other jobs from uploading at the same time.
+                  lock('build_gating_venv'){
+
+                    sh """#!/bin/bash -xeu
+                      # The repo path
+                      REPO_PATH="/var/www/repo/rpcgating/venvs"
+
+                      # Determine the SHA and archive name that we'll use
+                      pushd rpc-gating; SHA=\$(git rev-parse HEAD); popd
+                      archive="rpcgatingvenv_\${SHA}_test2.tbz"
+
+                      # Should we skip the upload? This file will exist from the previous step if we didn't generate a new archive.
+                      if [[ -e \$archive.skip.upload ]]; then
+                        echo "Archive \$REPO_PATH/\$archive already exists in the REPO and the virtual env build was previously skipped.  Skipping virtual env upload."
+                        exit 0
+                      fi
+
+                      # Set some SSH options
+                      SSH_OPTS="-o StrictHostKeyChecking=no"
+
+                      # Make sure the path exists...
+                      ssh \${SSH_OPTS} \$REPO_USER@\$REPO_HOST "mkdir -p \$REPO_PATH"
+
+                      # Upload generated version
+                      scp \$SSH_OPTS \$archive \$REPO_USER@\$REPO_HOST:\$REPO_PATH
+
+                      # Generate index
+                      ssh \$SSH_OPTS \$REPO_USER@\$REPO_HOST "cd \$REPO_PATH; ls -1 *tbz > index"
+
+                      # Keep 100 newest archives, remove the rest.
+                      ssh \$SSH_OPTS \$REPO_USER@\$REPO_HOST "cd \$REPO_PATH && ls -t1 *tbz |tail -n +101 |while read f; do echo "'removing \$f'"; rm "'\$f'"; done"
+                    """
+                  } // lock
                 } // sshagent
               } // container
             } // with credentials
